In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('data_to_model.csv')

In [3]:
df

daysOnMarket   price    zip  beds  baths   latitude  longitude  \
0              1.0  1855.0  11212     1    1.0  40.662186 -73.922293   
1              4.0  2235.0  11212     2    1.0  40.663817 -73.924122   
2              4.0  1750.0  11212     1    1.0  40.668506 -73.917055   
3              6.0  1850.0  11212     1    1.0  40.657349 -73.917750   
4              7.0  3000.0  11212     3    1.0  40.659825 -73.922602   
...            ...     ...    ...   ...    ...        ...        ...   
6966         121.0  4070.0  10459     4    1.0  40.823948 -73.889854   
6967           6.0  3800.0  10307     3    3.0  40.513058 -74.249470   
6968           5.0  3750.0  10038     2    1.0  40.709580 -74.009330   
6969          10.0  3200.0  10038     1    1.0  40.709370 -74.006035   
6970          12.0  7995.0  10038     2    2.0  40.709740 -74.006620   

      hasVideo  PhotosNum  Number of Households  ...  day_available  \
0            1          4               32091.0  ...             25   
1            1          5               32091.0  ...             22   
2            1          7               32091.0  ...             22   
3            1          4               32091.0  ...             20   
4            1          9               32091.0  ...             19   
...        ...        ...                   ...  ...            ...   
6966         0          0               17805.0  ...             15   
6967         0         18                5217.0  ...             15   
6968         0          5               10646.0  ...             15   
6969         0          0               10646.0  ...             15   
6970         0          0               10646.0  ...             15   

      beds_baths_interaction  log_monthly_housing_costs  \
0                        1.0                   7.087574   
1                        2.0                   7.087574   
2                        1.0                   7.087574   
3                        1.0                   7.087574   
4                        3.0                   7.087574   
...                      ...                        ...   
6966                     4.0                   7.188413   
6967                     9.0                   7.658228   
6968                     2.0                   7.921536   
6969                     1.0                   7.921536   
6970                     4.0                   7.921536   

      precinct_safety_rank_scaled  median_income_scaled  \
0                        1.393251             -1.454809   
1                        1.393251             -1.454809   
2                        1.539399             -1.454809   
3                        1.393251             -1.454809   
4                        1.393251             -1.454809   
...                           ...                   ...   
6966                     0.272790             -1.325090   
6967                    -1.627123              0.668903   
6968                     0.029211              0.069353   
6969                     0.029211              0.069353   
6970                     0.029211              0.069353   

      crime_to_safety_ratio  beds_to_baths_ratio  diversity_index  \
0                  0.029137             0.500000         0.000074   
1                  0.029137             1.000000         0.000074   
2                  0.029947             0.500000         0.000074   
3                  0.029137             0.500000         0.000074   
4                  0.029137             1.500000         0.000074   
...                     ...                  ...              ...   
6966               0.032050             2.000000         0.000073   
6967               0.205292             0.750000         0.000001   
6968               0.034026             1.000000         0.001610   
6969               0.034026             0.500000         0.001610   
6970               0.034026             0.666667         0.001610   

      occupied_to_vacant_ratio  price_bin

In [4]:
df = df.drop("price", axis = 1)

In [5]:
df

daysOnMarket    zip  beds  baths   latitude  longitude  hasVideo  \
0              1.0  11212     1    1.0  40.662186 -73.922293         1   
1              4.0  11212     2    1.0  40.663817 -73.924122         1   
2              4.0  11212     1    1.0  40.668506 -73.917055         1   
3              6.0  11212     1    1.0  40.657349 -73.917750         1   
4              7.0  11212     3    1.0  40.659825 -73.922602         1   
...            ...    ...   ...    ...        ...        ...       ...   
6966         121.0  10459     4    1.0  40.823948 -73.889854         0   
6967           6.0  10307     3    3.0  40.513058 -74.249470         0   
6968           5.0  10038     2    1.0  40.709580 -74.009330         0   
6969          10.0  10038     1    1.0  40.709370 -74.006035         0   
6970          12.0  10038     2    2.0  40.709740 -74.006620         0   

      PhotosNum  Number of Households  Median Household Income  ...  \
0             4               32091.0                  35840.0  ...   
1             5               32091.0                  35840.0  ...   
2             7               32091.0                  35840.0  ...   
3             4               32091.0                  35840.0  ...   
4             9               32091.0                  35840.0  ...   
...         ...                   ...                      ...  ...   
6966          0               17805.0                  41270.0  ...   
6967         18                5217.0                 124738.0  ...   
6968          5               10646.0                  99641.0  ...   
6969          0               10646.0                  99641.0  ...   
6970          0               10646.0                  99641.0  ...   

      day_available  beds_baths_interaction  log_monthly_housing_costs  \
0                25                     1.0                   7.087574   
1                22                     2.0                   7.087574   
2                22                     1.0                   7.087574   
3                20                     1.0                   7.087574   
4                19                     3.0                   7.087574   
...             ...                     ...                        ...   
6966             15                     4.0                   7.188413   
6967             15                     9.0                   7.658228   
6968             15                     2.0                   7.921536   
6969             15                     1.0                   7.921536   
6970             15                     4.0                   7.921536   

      precinct_safety_rank_scaled  median_income_scaled  \
0                        1.393251             -1.454809   
1                        1.393251             -1.454809   
2                        1.539399             -1.454809   
3                        1.393251             -1.454809   
4                        1.393251             -1.454809   
...                           ...                   ...   
6966                     0.272790             -1.325090   
6967                    -1.627123              0.668903   
6968                     0.029211              0.069353   
6969                     0.029211              0.069353   
6970                     0.029211              0.069353   

      crime_to_safety_ratio  beds_to_baths_ratio  diversity_index  \
0                  0.029137             0.500000         0.000074   
1                  0.029137             1.000000         0.000074   
2                  0.029947             0.500000         0.000074   
3                  0.029137             0.500000         0.000074   
4                  0.029137             1.500000         0.000074   
...                     ...                  ...              ...   
6966               0.032050             2.000000         0.000073   
6967               0.205292             0.750000         0.000001   
6968               0.034026             1.000

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from tqdm import tqdm

# Assuming df is your DataFrame and 'price_bin' is the target variable
X = df.drop(columns=['price_bin'])  # Features
y = df['price_bin']  # Target variable (price_bin)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the classifiers you want to compare
models = {
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'KNN': KNeighborsClassifier()
}

# Dictionary to store model performance
results = {}

# Use tqdm to monitor progress
for model_name, model in tqdm(models.items(), desc="Training Models", total=len(models)):
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Evaluate the model performance
    accuracy = accuracy_score(y_test, y_pred)
    confusion = confusion_matrix(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    
    # Store results
    results[model_name] = {
        'Accuracy': accuracy,
        'Confusion Matrix': confusion,
        'Classification Report': classification_rep
    }

    # Print results
    print(f"Model: {model_name}")
    print(f"Accuracy: {accuracy}")
    print(f"Confusion Matrix:\n{confusion}")
    print(f"Classification Report:\n{classification_rep}")
    print("-" * 50)

# Optionally, you can store results in a DataFrame for easy comparison
comparison_df = pd.DataFrame({
    'Model': list(results.keys()),
    'Accuracy': [results[model]['Accuracy'] for model in results],
})

print(comparison_df)


Training Models:  20%|█████▌                      | 1/5 [00:00<00:02,  1.43it/s]

Model: Random Forest
Accuracy: 0.7949820788530466
Confusion Matrix:
[[451 120   0]
 [118 514  12]
 [  2  34 144]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.79      0.79       571
           1       0.77      0.80      0.78       644
           2       0.92      0.80      0.86       180

    accuracy                           0.79      1395
   macro avg       0.83      0.80      0.81      1395
weighted avg       0.80      0.79      0.80      1395

--------------------------------------------------


/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Training Mode

Model: SVM
Accuracy: 0.47168458781362005
Confusion Matrix:
[[ 19 552   0]
 [  5 639   0]
 [  0 180   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.03      0.06       571
           1       0.47      0.99      0.63       644
           2       0.00      0.00      0.00       180

    accuracy                           0.47      1395
   macro avg       0.42      0.34      0.23      1395
weighted avg       0.54      0.47      0.32      1395

--------------------------------------------------


/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
Training Models:  80%|██████████████████████▍     | 4/5 [00:02<00:00,  1.38it/s]


Model: Logistic Regression
Accuracy: 0.5526881720430108
Confusion Matrix:
[[357 191  23]
 [242 350  52]
 [ 18  98  64]]
Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.63      0.60       571
           1       0.55      0.54      0.55       644
           2       0.46      0.36      0.40       180

    accuracy                           0.55      1395
   macro avg       0.53      0.51      0.52      1395
weighted avg       0.55      0.55      0.55      1395

--------------------------------------------------
Model: Decision Tree
Accuracy: 0.7405017921146954
Confusion Matrix:
[[428 142   1]
 [150 458  36]
 [  2  31 147]]
Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.75      0.74       571
           1       0.73      0.71      0.72       644
           2       0.80      0.82      0.81       180

    accuracy                           0.74      1395
   macro avg    

AttributeError: 'Flags' object has no attribute 'c_contiguous'

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from tqdm import tqdm

# Assuming df is your DataFrame and 'price_bin' is the target variable
X = df.drop(columns=['price_bin'])  # Features
y = df['price_bin']  # Target variable (price_bin)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ensure data is in numeric format (convert if necessary)
X_train = X_train.values
X_test = X_test.values

# Initialize the classifiers you want to compare
models = {
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'KNN': KNeighborsClassifier()
}

# Dictionary to store model performance
results = {}

# Use tqdm to monitor progress
for model_name, model in tqdm(models.items(), desc="Training Models", total=len(models)):
    try:
        # Train the model
        model.fit(X_train, y_train)
        
        # Make predictions
        y_pred = model.predict(X_test)
        
        # Evaluate the model performance
        accuracy = accuracy_score(y_test, y_pred)
        confusion = confusion_matrix(y_test, y_pred)
        classification_rep = classification_report(y_test, y_pred)
        
        # Store results
        results[model_name] = {
            'Accuracy': accuracy,
            'Confusion Matrix': confusion,
            'Classification Report': classification_rep
        }

        # Print results
        print(f"Model: {model_name}")
        print(f"Accuracy: {accuracy}")
        print(f"Confusion Matrix:\n{confusion}")
        print(f"Classification Report:\n{classification_rep}")
        print("-" * 50)

    except Exception as e:
        print(f"Error in training {model_name}: {e}")

# Optionally, you can store results in a DataFrame for easy comparison
comparison_df = pd.DataFrame({
    'Model': list(results.keys()),
    'Accuracy': [results[model]['Accuracy'] for model in results],
})

print(comparison_df)


Training Models:  20%|█████▌                      | 1/5 [00:00<00:02,  1.43it/s]

Model: Random Forest
Accuracy: 0.792831541218638
Confusion Matrix:
[[454 117   0]
 [119 508  17]
 [  2  34 144]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.80      0.79       571
           1       0.77      0.79      0.78       644
           2       0.89      0.80      0.84       180

    accuracy                           0.79      1395
   macro avg       0.82      0.79      0.81      1395
weighted avg       0.79      0.79      0.79      1395

--------------------------------------------------


/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Training Mode

Model: SVM
Accuracy: 0.47168458781362005
Confusion Matrix:
[[ 19 552   0]
 [  5 639   0]
 [  0 180   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.03      0.06       571
           1       0.47      0.99      0.63       644
           2       0.00      0.00      0.00       180

    accuracy                           0.47      1395
   macro avg       0.42      0.34      0.23      1395
weighted avg       0.54      0.47      0.32      1395

--------------------------------------------------
Model: Logistic Regression
Accuracy: 0.5526881720430108
Confusion Matrix:
[[357 191  23]
 [242 350  52]
 [ 18  98  64]]
Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.63      0.60       571
           1       0.55      0.54      0.55       644
           2       0.46      0.36      0.40       180

    accuracy                           0.55      1395
   macro avg       0.53  

Training Models:  80%|██████████████████████▍     | 4/5 [00:02<00:00,  1.98it/s]

Model: Decision Tree
Accuracy: 0.7333333333333333
Confusion Matrix:
[[425 144   2]
 [162 450  32]
 [  4  28 148]]
Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.74      0.73       571
           1       0.72      0.70      0.71       644
           2       0.81      0.82      0.82       180

    accuracy                           0.73      1395
   macro avg       0.75      0.76      0.75      1395
weighted avg       0.73      0.73      0.73      1395

--------------------------------------------------


Training Models: 100%|████████████████████████████| 5/5 [00:02<00:00,  1.69it/s]

Model: KNN
Accuracy: 0.5663082437275986
Confusion Matrix:
[[380 184   7]
 [251 360  33]
 [ 27 103  50]]
Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.67      0.62       571
           1       0.56      0.56      0.56       644
           2       0.56      0.28      0.37       180

    accuracy                           0.57      1395
   macro avg       0.56      0.50      0.52      1395
weighted avg       0.56      0.57      0.56      1395

--------------------------------------------------
                 Model  Accuracy
0        Random Forest  0.792832
1                  SVM  0.471685
2  Logistic Regression  0.552688
3        Decision Tree  0.733333
4                  KNN  0.566308


In [10]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from tqdm import tqdm

# Assuming df is your DataFrame and 'price_bin' is the target variable
X = df.drop(columns=['price_bin'])  # Features
y = df['price_bin']  # Target variable (price_bin)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ensure data is in numeric format (convert if necessary)
X_train = X_train.values
X_test = X_test.values

# Define hyperparameter grids for each model
param_grids = {
    'Random Forest': {
        'n_estimators': [100, 200, 300],
        'max_depth': [None, 10, 20, 30]
    },
    'SVM': {
        'C': [1],
        'kernel': ['linear']
    },
    'Logistic Regression': {
        'C': [0.1, 1, 10],
        'solver': ['lbfgs', 'liblinear']
    },
    'Decision Tree': {
        'max_depth': [None, 10, 20, 30],
        'min_samples_split': [2, 5, 10]
    },
    'KNN': {
        'n_neighbors': [3, 5, 7, 10],
        'weights': ['uniform', 'distance']
    }
}

# Initialize the classifiers
models = {
    'Random Forest': RandomForestClassifier(),
#     'SVM': SVC(),
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'KNN': KNeighborsClassifier()
}

# Dictionary to store model performance
results = {}

# Use tqdm to monitor progress
for model_name, model in tqdm(models.items(), desc="Training Models", total=len(models)):
    try:
        # Perform GridSearchCV for minimal hyperparameter tuning
        grid_search = GridSearchCV(estimator=model, param_grid=param_grids[model_name], cv=3, n_jobs=-1, verbose=0)
        grid_search.fit(X_train, y_train)

        # Get the best model from the grid search
        best_model = grid_search.best_estimator_

        # Make predictions
        y_pred = best_model.predict(X_test)

        # Evaluate the model performance
        accuracy = accuracy_score(y_test, y_pred)
        confusion = confusion_matrix(y_test, y_pred)
        classification_rep = classification_report(y_test, y_pred)
        
        # Store results
        results[model_name] = {
            'Best Params': grid_search.best_params_,
            'Accuracy': accuracy,
            'Confusion Matrix': confusion,
            'Classification Report': classification_rep
        }

        # Print results
        print(f"Model: {model_name}")
        print(f"Best Params: {grid_search.best_params_}")
        print(f"Accuracy: {accuracy}")
        print(f"Confusion Matrix:\n{confusion}")
        print(f"Classification Report:\n{classification_rep}")
        print("-" * 50)

    except Exception as e:
        print(f"Error in training {model_name}: {e}")

# Optionally, you can store results in a DataFrame for easy comparison
comparison_df = pd.DataFrame({
    'Model': list(results.keys()),
    'Best Params': [results[model]['Best Params'] for model in results],
    'Accuracy': [results[model]['Accuracy'] for model in results],
})

print(comparison_df)


Training Models:  25%|███████                     | 1/4 [00:07<00:23,  7.88s/it]

Model: Random Forest
Best Params: {'max_depth': 10, 'n_estimators': 300}
Accuracy: 0.7985663082437277
Confusion Matrix:
[[449 122   0]
 [102 530  12]
 [  4  41 135]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.79      0.80       571
           1       0.76      0.82      0.79       644
           2       0.92      0.75      0.83       180

    accuracy                           0.80      1395
   macro avg       0.83      0.79      0.81      1395
weighted avg       0.80      0.80      0.80      1395

--------------------------------------------------


/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/nikhilsoni/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#l

Model: Logistic Regression
Best Params: {'C': 0.1, 'solver': 'liblinear'}
Accuracy: 0.5655913978494623
Confusion Matrix:
[[440 127   4]
 [312 312  20]
 [ 21 122  37]]
Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.77      0.65       571
           1       0.56      0.48      0.52       644
           2       0.61      0.21      0.31       180

    accuracy                           0.57      1395
   macro avg       0.58      0.49      0.49      1395
weighted avg       0.57      0.57      0.55      1395

--------------------------------------------------


Training Models:  75%|█████████████████████       | 3/4 [00:09<00:02,  2.21s/it]

Model: Decision Tree
Best Params: {'max_depth': 10, 'min_samples_split': 5}
Accuracy: 0.7727598566308244
Confusion Matrix:
[[457 113   1]
 [150 472  22]
 [  3  28 149]]
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.80      0.77       571
           1       0.77      0.73      0.75       644
           2       0.87      0.83      0.85       180

    accuracy                           0.77      1395
   macro avg       0.80      0.79      0.79      1395
weighted avg       0.77      0.77      0.77      1395

--------------------------------------------------


Training Models: 100%|████████████████████████████| 4/4 [00:09<00:00,  2.40s/it]

Model: KNN
Best Params: {'n_neighbors': 10, 'weights': 'uniform'}
Accuracy: 0.5985663082437276
Confusion Matrix:
[[412 151   8]
 [248 377  19]
 [ 22 112  46]]
Classification Report:
              precision    recall  f1-score   support

           0       0.60      0.72      0.66       571
           1       0.59      0.59      0.59       644
           2       0.63      0.26      0.36       180

    accuracy                           0.60      1395
   macro avg       0.61      0.52      0.54      1395
weighted avg       0.60      0.60      0.59      1395

--------------------------------------------------
                 Model                                Best Params  Accuracy
0        Random Forest     {'max_depth': 10, 'n_estimators': 300}  0.798566
1  Logistic Regression          {'C': 0.1, 'solver': 'liblinear'}  0.565591
2        Decision Tree  {'max_depth': 10, 'min_samples_split': 5}  0.772760
3                  KNN  {'n_neighbors': 10, 'weights': 'uniform'}  0.598566
